name: fun
maintainer: ACME
category: Other
synopsis: A functional language.
description: Experiments implementing a simple functional language in Haskell.
version: '0.1'

extra-source-files:
- package.yaml

ghc-options: >-
  -Wall
  -Wincomplete-record-updates
  -Wincomplete-uni-patterns
dependencies:
- aeson
- async
- base
- bytestring
- clock
- containers
- conduit
- conduit-extra
- deepseq
- hashable
- hspec
- kan-extensions
- lens
- mtl
- network
- optparse-applicative
- QuickCheck
- text
- transformers
- unordered-containers
- vector

library:
  source-dirs: src

executables:
  fun:
    dependencies:
      - fun
    ghc-options:
      - -rtsopts
      - -threaded
      - '"-with-rtsopts=-T -N -A32m -n4m -qg"'
    main: app/Main.hs

tests:
  fun-tests:
    dependencies:
      - fun
    ghc-options:
      - -rtsopts
      - -threaded
      - '"-with-rtsopts=-T -N -A32m -n4m -qg"'
    main: Spec.hs
    source-dirs: tests